### ISSUE TITLE
Git clone

### ISSUE THREAD

**Issue by evil-potato** [WalkerLau/GPU-CNN#1]
您好，我是从西电睿思上面看到一直关注之前FPGA的那个神经网络的加速项目，现在想要下载您的这个GPU的这个项目，但是里面的modul里面的那个大文件一直下载不下来，请问有别的方式下载您的整个工程文件吗？

**Comment by WalkerLau** [comment]
> 您好，我是从西电睿思上面看到一直关注之前FPGA的那个神经网络的加速项目，现在想要下载您的这个GPU的这个项目，但是里面的modul里面的那个大文件一直下载不下来，请问有别的方式下载您的整个工程文件吗？

同学你好，你可以：
1. 在网页版的model目录中点击Download按钮下载这个文件，只是速度可能有点慢。
2. 你也可以直接下载
https://github.com/WalkerLau/Accelerating-CNN-with-FPGA
这个repo，进入同名文件夹，解压里面的两个参数文件压缩包，可以得到同样的参数文件。
